### ISSUE TITLE
Better usage example

### ISSUE THREAD

**Issue by spacekookie** [legolord208/insult#2]
Hey there, just saw your crate pop up on crates.io

I'm kinda wondering how it would be possible to use this in my application, without having to provide my own word files? It looks like the crate already includes the strings at compile-time, but looking at the API I can't figure out how to initialise a generator that uses them.

Could you maybe help be out there, or add an example for that? Thanks :slightly_smiling_face:

**Comment by jD91mZM2** [comment]
You're in luck! It didn't actually include any word files in the library itself until the latest version - which was the one you saw popup.

One example you can use currently is the source code behind the wasm example on my website ([here](https://github.com/jD91mZM2/jD91mZM2.github.io/blob/master/wasm/src/wasm_insult.rs#L19-L25)).
I'll add an official example ASAP.

**Comment by spacekookie** [comment]
Ah, that's nice, thanks :)

Also thanks for releasing a new version of the library on my birthday. It's a nice present :joy:

**Comment by jD91mZM2** [comment]
Sorry for the late reply, I fixed it in 623ee10129a0b0ff7cdd2e25ff7147276b6a4da2 but forgot to tell you so. It's been a busy day :stuck_out_tongue:
